apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
  
namespace: homolog


images:
- name: goapp
  newName: fernandojpessoa/argocd-fullcycle
  newTag: 0f0479710c20b93b63be04d245c3bf6b9fb17af6
